
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Ilhaan Hasan",
    "dateOfBirth": "1991-04-25",
    "ssn": "250770-555L",
    "gender": "male",
    "occupation": "SW Developer"
}
